<?php
/**
 * Layout Builder Admin Page
 *
 * Provides drag-and-drop layout builder interface for tournament displays
 *
 * @package Poker_Tournament_Import
 * @subpackage Tournament_Manager
 * @since 3.4.0
 */

// Prevent direct file access
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Layout Builder admin page class
 *
 * @since 3.4.0
 */
class TDWP_Layout_Builder_Page {

	/**
	 * Layout builder instance
	 *
	 * @var TDWP_Layout_Builder
	 */
	private $layout_builder;

	/**
	 * Constructor
	 *
	 * @since 3.4.0
	 */
	public function __construct() {
		$this->layout_builder = TDWP_Layout_Builder::get_instance();

		// Add admin menu
		add_action( 'admin_menu', array( $this, 'add_admin_menu' ) );

		// Enqueue admin assets
		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_admin_assets' ) );
	}

	/**
	 * Add admin menu item
	 *
	 * @since 3.4.0
	 */
	public function add_admin_menu() {
		add_submenu_page(
			'tdwp-tournament-manager',
			__( 'TD3 Layout Builder', 'poker-tournament-import' ),
			__( 'Layout Builder', 'poker-tournament-import' ),
			'manage_options',
			'tdwp-layout-builder',
			array( $this, 'render_admin_page' )
		);
	}

	/**
	 * Enqueue admin assets
	 *
	 * @since 3.4.0
	 * @param string $hook Current admin page hook.
	 */
	public function enqueue_admin_assets( $hook ) {
		// Only load on layout builder page
		if ( 'tournament-manager_page_tdwp-layout-builder' !== $hook ) {
			return;
		}

		// Enqueue jQuery UI dependencies
		wp_enqueue_style( 'wp-jquery-ui-dialog' );
		wp_enqueue_script( 'jquery-ui-draggable' );
		wp_enqueue_script( 'jquery-ui-droppable' );
		wp_enqueue_script( 'jquery-ui-sortable' );

		// Enqueue layout builder script
		wp_enqueue_script(
			'tdwp-layout-builder',
			POKER_TOURNAMENT_IMPORT_PLUGIN_URL . 'assets/js/layout-builder.js',
			array( 'jquery', 'jquery-ui-draggable', 'jquery-ui-droppable', 'jquery-ui-sortable' ),
			POKER_TOURNAMENT_IMPORT_VERSION,
			true
		);
	}

	/**
	 * Render layout builder admin page
	 *
	 * @since 3.4.0
	 */
	public function render_admin_page() {
		// Get the main admin class to render simple layout
		global $poker_tournament_admin;

		if ( ! $poker_tournament_admin ) {
			// Fallback: instantiate admin class if not available
			$poker_tournament_admin = new Poker_Tournament_Import_Admin();
		}

		// Call the simple layout renderer
		$poker_tournament_admin->render_layout_builder_page();
	}

	/**
	 * Render layout builder page
	 *
	 * @since 3.4.0
	 * @param int $tournament_id Tournament ID.
	 */
	public function render_page( $tournament_id ) {
		?>
		<div class="wrap">
			<h1 class="wp-heading-inline">
				Layout Builder
				<a href="#" class="page-title-action tdwp-layout-preview-btn" data-tournament="<?php echo esc_attr( $tournament_id ); ?>">
					Preview Layout
				</a>
			</h1>

			<div class="tdwp-layout-builder-container">
				<!-- Toolbar -->
				<div class="tdwp-layout-toolbar">
					<div class="tdwp-toolbar-left">
						<select id="tdwp-layout-select" class="regular-text">
							<option value="">Create New Layout</option>
							<?php $this->render_existing_layouts( $tournament_id ); ?>
						</select>
						<button id="tdwp-new-layout-btn" class="button button-secondary">
							New Layout
						</button>
						<button id="tdwp-save-layout-btn" class="button button-primary" disabled>
							Save Layout
						</button>
						<button id="tdwp-delete-layout-btn" class="button button-link-delete" disabled>
							Delete Layout
						</button>
					</div>
					<div class="tdwp-toolbar-right">
						<select id="tdwp-device-preview" class="regular-text">
							<option value="desktop">Desktop (1920x1080)</option>
							<option value="tablet">Tablet (1024x768)</option>
							<option value="mobile">Mobile (375x667)</option>
							<option value="large">Large Display (2560x1440)</option>
						</select>
						<button id="tdwp-grid-toggle" class="button button-secondary" data-active="true">
							Show Grid
						</button>
						<button id="tdwp-reset-layout" class="button button-link-delete">
							Reset Layout
						</button>
					</div>
				</div>

				<!-- Main Layout Area -->
				<div class="tdwp-layout-main">
					<!-- Component Palette -->
					<div class="tdwp-component-palette">
						<h3>Components</h3>
						<div class="tdwp-component-categories">
							<ul class="tdwp-component-list">
								<?php $this->render_component_palette(); ?>
							</ul>
						</div>
					</div>

					<!-- Layout Canvas -->
					<div class="tdwp-layout-canvas-container">
						<div class="tdwp-layout-canvas" id="tdwp-layout-canvas">
							<div class="tdwp-layout-grid" id="tdwp-layout-grid">
								<!-- Grid cells will be generated by JavaScript -->
							</div>
							<!-- Dropped components will be added here -->
						</div>
					</div>

					<!-- Properties Panel -->
					<div class="tdwp-properties-panel">
						<h3>Properties</h3>
						<div id="tdwp-properties-content">
							<p class="description">Select a component to edit its properties</p>
						</div>
					</div>
				</div>

				<!-- Status Bar -->
				<div class="tdwp-layout-status">
					<span class="tdwp-status-left">
						<span id="tdwp-grid-info">12×8 Grid</span>
						<span id="tdwp-component-count">0 Components</span>
					</span>
					<span class="tdwp-status-right">
						<span id="tdwp-layout-status" class="tdwp-status-ready">Ready</span>
						<span id="tdwp-last-saved"></span>
					</span>
				</div>
			</div>

			<!-- Hidden data -->
			<div id="tdwp-layout-data" style="display: none;"
				data-tournament-id="<?php echo esc_attr( $tournament_id ); ?>"
				data-nonce="<?php echo esc_attr( wp_create_nonce( 'tdwp_layout_nonce' ) ); ?>"
				data-available-components="<?php echo esc_attr( json_encode( $this->layout_builder->get_available_components() ) ); ?>"
				data-breakpoints="<?php echo esc_attr( json_encode( $this->layout_builder->get_breakpoints() ) ); ?>">
			</div>
		</div>

		<!-- Preview Modal -->
		<div id="tdwp-preview-modal" class="tdwp-modal" style="display: none;">
			<div class="tdwp-modal-content">
				<div class="tdwp-modal-header">
					<h2>Layout Preview</h2>
					<button class="tdwp-modal-close">&times;</button>
				</div>
				<div class="tdwp-modal-body">
					<iframe id="tdwp-preview-frame" src="" width="100%" height="600"></iframe>
				</div>
			</div>
		</div>
		<?php
	}

	/**
	 * Render existing layouts dropdown
	 *
	 * @since 3.4.0
	 * @param int $tournament_id Tournament ID.
	 */
	private function render_existing_layouts( $tournament_id ) {
		global $wpdb;

		$layouts = $wpdb->get_results( $wpdb->prepare(
			"SELECT layout_id, layout_name, screen_size, is_active
			 FROM {$wpdb->prefix}poker_display_layouts
			 WHERE tournament_id = %d
			 ORDER BY layout_name",
			$tournament_id
		) );

		foreach ( $layouts as $layout ) {
			$selected = $layout->is_active ? 'selected' : '';
			echo '<option value="' . esc_attr( $layout->layout_id ) . '" ' . $selected . '>';
			echo esc_html( $layout->layout_name );
			if ( $layout->screen_size ) {
				echo ' (' . esc_html( $layout->screen_size ) . ')';
			}
			echo '</option>';
		}
	}

	/**
	 * Render component palette
	 *
	 * @since 3.4.0
	 */
	private function render_component_palette() {
		$components = $this->layout_builder->get_available_components();

		foreach ( $components as $component_id => $component ) {
			echo '<li class="tdwp-component-item" data-component="' . esc_attr( $component_id ) . '">';
			echo '<div class="tdwp-component-icon">' . esc_html( $this->get_component_icon( $component_id ) ) . '</div>';
			echo '<div class="tdwp-component-label">' . esc_html( $component['name'] ) . '</div>';
			echo '</li>';
		}
	}

	/**
	 * Get component icon
	 *
	 * @since 3.4.0
	 * @param string $component_id Component ID.
	 * @return string Icon HTML.
	 */
	private function get_component_icon( $component_id ) {
		$icons = array(
			'tournament_name' => '🏆',
			'clock_display' => '⏰',
			'current_blinds' => '💰',
			'time_remaining' => '⏳',
			'player_count' => '👥',
			'prize_pool' => '💎',
			'rankings' => '📊',
			'seating_chart' => '🪑',
			'next_blinds' => '⬆️',
			'custom_content' => '📝',
		);

		return $icons[ $component_id ] ?? '📦';
	}

	/**
	 * Render layout properties panel
	 *
	 * @since 3.4.0
	 * @param array $component Component data.
	 */
	public function render_properties_panel( $component ) {
		if ( empty( $component ) ) {
			return;
		}

		?>
		<div class="tdwp-property-group">
			<h4>Component Properties</h4>
			<table class="tdwp-property-table">
				<tr>
					<td><label>Type:</label></td>
					<td><?php echo esc_html( $component['name'] ); ?></td>
				</tr>
				<tr>
					<td><label>Width:</label></td>
					<td>
						<input type="number" id="tdwp-prop-width" class="small-text"
							value="<?php echo esc_attr( $component['width'] ); ?>" min="1" max="24">
						<span class="tdwp-property-unit">columns</span>
					</td>
				</tr>
				<tr>
					<td><label>Height:</label></td>
					<td>
						<input type="number" id="tdwp-prop-height" class="small-text"
							value="<?php echo esc_attr( $component['height'] ); ?>" min="1" max="20">
						<span class="tdwp-property-unit">rows</span>
					</td>
				</tr>
			</table>
		</div>

		<div class="tdwp-property-group">
			<h4>Appearance</h4>
			<table class="tdwp-property-table">
				<tr>
					<td><label>Background:</label></td>
					<td>
						<input type="color" id="tdwp-prop-bg-color" class="tdwp-color-picker"
							value="<?php echo esc_attr( $component['bg_color'] ?? '#ffffff' ); ?>">
					</td>
				</tr>
				<tr>
					<td><label>Text Color:</label></td>
					<td>
						<input type="color" id="tdwp-prop-text-color" class="tdwp-color-picker"
							value="<?php echo esc_attr( $component['text_color'] ?? '#000000' ); ?>">
					</td>
				</tr>
				<tr>
					<td><label>Font Size:</label></td>
					<td>
						<input type="number" id="tdwp-prop-font-size" class="small-text"
							value="<?php echo esc_attr( $component['font_size'] ?? 16 ); ?>" min="8" max="72">
						<span class="tdwp-property-unit">px</span>
					</td>
				</tr>
			</table>
		</div>

		<div class="tdwp-property-group">
			<h4>Actions</h4>
			<button id="tdwp-apply-properties" class="button button-secondary">
				Apply Changes
			</button>
			<button id="tdwp-delete-component" class="button button-link-delete">
				Delete Component
			</button>
		</div>
		<?php
	}
}

// Instantiate the layout builder page
if ( class_exists( 'TDWP_Layout_Builder' ) ) {
	new TDWP_Layout_Builder_Page();
}